steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'submodule'
  - 'update'
  - '--init'
  - '--recursive'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wetc-buyback-service:latest'
  - '-f'
  - 'Service.Dockerfile'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wetc-buyback-service:latest'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'wetc-buyback-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/wetc-buyback-service:latest'
    - '--region'
    - 'us-central1'
images: ['gcr.io/$PROJECT_ID/wetc-buyback-service:latest']
